models/Agents.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Agents extends ActiveRecord
{

    public function rules()
    {
        return [
            ['name', 'required'],
        ];
    }

    public function getPhoneNumbers()
    {
        return $this->hasMany(PhoneNumbers::className(), ['agent_id' => 'id']);
    }


}

controllers/AgentController.php
<?php

namespace app\controllers;

use app\models\Agents;
use app\models\forms\AgentForm;
use app\services\TwilioService;
use yii\helpers\Url;
use yii\web\Controller;

class AgentController extends Controller
{
    private $twilio;

    public function __construct($id,  $module, TwilioService $twilioService, array $config = [])
    {
        parent::__construct($id, $module, $config);

        $this->twilio = $twilioService;
    }

    public function actionIndex()
    {
        $agents = Agents::find()->all();

        return $this->render('index', [
            'agents' => $agents
        ]);
    }

    public function actionCreate()
    {
        $agentForm = new AgentForm();
        return $this->render('create', [
            'agentForm' => $agentForm
        ]);
    }

    public function actionStore()
    {

        $data = \Yii::$app->request->post();

        $agent = new Agents();
        $agent->load($data, 'AgentForm');
        if($agent->save()){
            return $this->redirect('/agent/index');

        }
        return $this->redirect(\Yii::$app->request->referrer);

    }

    public function actionEdit($id)
    {
        $agent = Agents::find()
            ->where(['id' => $id])
            ->one();

        if(!$agent) {
            return $this->redirect(\Yii::$app->request->referrer);
        }

        $agentForm = new AgentForm();
        return $this->render('edit', [
            'agentForm' => $agentForm,
            'agent' => $agent
        ]);
    }

    public function actionUpdate($id)
    {
        $data = \Yii::$app->request->post();

        $agent = Agents::find()
            ->where(['id' => $id])
            ->one();

        if($agent){
            $agent->load($data);
            if($agent->save()) {
                return $this->redirect('/agent/index');
            }
        }

        return $this->redirect(\Yii::$app->request->referrer);
    }

    public function actionDelete($id)
    {
        $agent = Agents::find()
            ->where(['id' => $id])
            ->with('phoneNumbers')
            ->one();

        if(!$agent) {
            return $this->redirect(\Yii::$app->request->referrer);
        }

        foreach($agent->phoneNumbers as $phoneNumber) {
            $this->twilio->releasePhoneNumber($phoneNumber->phone_number_sid);
            $phoneNumber->delete();
        }

        $agent->delete();
        return $this->redirect('/agent/index');
    }

    public function actionShow($id)
    {
        $agent = Agents::findOne($id);

        if(!$agent)
            return $this->redirect(\Yii::$app->request->referrer);

        return $this->render('show', [
            'agent' => $agent,
            'phoneNumbers' => $agent->phoneNumbers,
        ]);

    }
}

controllers/PhoneController.php
<?php

namespace app\controllers;

use app\models\Agents;
use app\models\forms\AgentForm;
use app\models\PhoneNumbers;
use app\services\TwilioService;
use yii\base\DynamicModel;
use yii\base\Module;
use yii\helpers\Url;
use yii\web\Controller;


class PhoneController extends Controller
{
    private $twilio;

    public function __construct($id, Module $module, TwilioService $twilioService, array $config = [])
    {
        parent::__construct($id, $module, $config);

        $this->twilio = $twilioService;
    }

    public function actionCreate($agent_id)
    {
        $agent = Agents::findOne($agent_id);

        if(!$agent) {
            return $this->redirect(\Yii::$app->request->referrer);
        }

        $availableCountries = $this->twilio->getCountries();

        return $this->render('create', [
            'countries' => $availableCountries,
            'agent' => $agent,
            'phone' => new PhoneNumbers(),
        ]);
    }

    public function actionSelectPhone($id)
    {
        $agent = Agents::findOne($id);
        $data = \Yii::$app->request->post();

        $phoneNumbers = $this->twilio->getPhoneNumbersForCountry($data['PhoneNumbers']['country']);
        if ($phoneNumbers !== false) {
            return $this->render('phone-select', [
                'country' => $data['PhoneNumbers']['country'],
                'agent' => $agent,
                'phone' => new PhoneNumbers(),
                'phoneNumbers' => $phoneNumbers
            ]);
        } else {
            return 'twilio error: '.$this->twilio->getError();
        }

    }

    public function actionStore()
    {
        $data = \Yii::$app->request->post();
        $phoneNumber = new PhoneNumbers();
        $phoneNumber->load($data);

        $phoneNumberSid = $this->twilio->buyPhoneNumber($phoneNumber->phone_number);
        if(!$phoneNumberSid){
            return 'twilio error: '.$this->twilio->getError();
        }

        $phoneNumber->phone_number_sid = $phoneNumberSid;

        $phoneNumber->save();

        return $this->redirect(['/agent/show', 'id' => $phoneNumber->agent_id]);
    }

    public function actionRelease($phone_id)
    {
        $phoneNumber = PhoneNumbers::findOne($phone_id);
        if(!$phoneNumber)
            return $this->redirect(\Yii::$app->request->referrer);

        $success = $this->twilio->releasePhoneNumber($phoneNumber->phone_number_sid);
        if(!$success)
            return $this->twilio->getError();

        $phoneNumber->delete();
        return $this->redirect(['/agent/show', 'id' => $phoneNumber->agent_id]);
    }
}

views/agent/create.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<?php $form = ActiveForm::begin(['action' => ['/agent/store'], 'options' => ['method' => 'post']]) ?>
    <?= $form->field($agentForm, 'name') ?>
    <?= Html::submitButton('Send', ['class' => 'btn btn-success']) ?>
<?php ActiveForm::end() ?>

views/agent/edit.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<?php $form = ActiveForm::begin(['action' => ['/agent/update', 'id' => $agent->id], 'options' => ['method' => 'post']]) ?>
    <?= $form->field($agent, 'name') ?>
    <?= Html::submitButton('Send', ['class' => 'btn btn-success']) ?>
<?php ActiveForm::end() ?>

views/agent/index.php
<?php //$this->beginBlock('agents'); ?>

<div>
    <a href="<?= \yii\helpers\Url::to('/agent/create'); ?> " class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Add agent</a>
</div>
    <table class="table">
        <?php foreach($agents as $agent): ?>
            <tr>
                <td><?= \yii\helpers\Html::encode($agent->name)?> </td>

                <td>
                    <a href="<?= \yii\helpers\Url::to(['/agent/delete', 'id' => $agent->id]); ?>"> delete </a> |
                    <a href="<?= \yii\helpers\Url::to(['/agent/edit', 'id' => $agent->id]) ?>" > update </a> |
                    <a href="<?= \yii\helpers\Url::to(['/agent/show', 'id' => $agent->id]) ?>" > show </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

<?php //$this->endBlock(); ?>
<!---->
<!--    ...-->
<!---->

views/agent/show.php
<h2> <?= \yii\helpers\Html::encode($agent->name) ?> - phone numbers </h2>
<div>
    <a href="<?= \yii\helpers\Url::to(['/phone/create', 'agent_id' => $agent->id]); ?> " class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Add phone number</a>
</div>
<table class="table">
    <tr>
        <td> Phone number</td>
        <td> Action </td>
    </tr>
    <?php foreach($phoneNumbers as $phoneNumber): ?>
        <tr>
            <td>
                <?= \yii\helpers\Html::encode($phoneNumber->phone_number) ?>
            </td>
            <td>
                <a href="<?= \yii\helpers\Url::to(['phone/release', 'phone_id' => $phoneNumber->id]) ?>"> Release </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>